pipeline {
    agent any
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Build") {
            steps {
                dir("jdbc-data-generation-sql-script") {
                    bat "mvn clean install"
                }
            }
        }
        stage("Test") {
            steps {
                dir("jdbc-data-generation-sql-script") {
                    bat "mvn test"
                }
            }
        }
    }
}